
version: '3.4'

services:
  postgres:
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  shortener:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8005
    depends_on:
      - postgres
    volumes:
      - ..:/app
    ports:
      - "8005:8005"

volumes:
  postgres-data: {}