# Generated by Django 3.0.3 on 2020-07-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tinyurl',
            index=models.Index(fields=['short_url_hash'], name='shortner_ti_short_u_14da59_idx'),
        ),
    ]
